### ISSUE TITLE
setTime() does not set system time

### ISSUE THREAD

**Issue by rnsi** [khoih-prog/DS323x_Generic#1]
### Describe the bug

According to the docs, setTime() will "// set the system time to UTC". However time() still reports uptime seconds.

### Steps to Reproduce

In DS323x_Generic/examples/Time/ESP/RTC_ESP/RTC_ESP.ino , call time() function.

### Expected behavior

time() should contain the same value as rtc.now()

### Actual behavior

time() is unaffected.

### Information

Please ensure to specify the following:

* Arduino IDE version 1.8.19
* `ESP8266` Core Version ESP8266 core v3.0.0
* Contextual information - set system time from RTC
* Call time() function from RTC_ESP example
  
```

**Comment by khoih-prog** [comment]
The `setTime()` function is one of the [TimeLib library](https://github.com/PaulStoffregen/Time/blob/master/Time.cpp#L274) and it certainly can't know about every board to set the system time. You can post an issue there to ask for help.

Also check the similar issue in ESP8266 Forum [**TIMELIB : HOW TO SET TIME(NULLPTR) ?**](https://www.esp8266.com/viewtopic.php?f=32&t=22228)

You can also adapt this [**NTP-TZ-DST** example](https://github.com/esp8266/Arduino/blob/master/libraries/esp8266/examples/NTP-TZ-DST/NTP-TZ-DST.ino) to use.

**It's your responsibility to set the system time yourself, if you'd like to use, when you already have the accurate time from RTC.**

As this issue has nothing to do with this library, I'm closing it now.

Good Luck,

**Comment by khoih-prog** [comment]
Hi @rnsi 

I already write a new example [RTC_ESP_Complex](https://github.com/khoih-prog/DS323x_Generic/tree/main/examples/Time/ESP/RTC_ESP_Complex) to serve your purpose.

The terminal output when running on **ESP8266_NODEMCU_ESP12E**

```
Start RTC_ESP_Complex on ESP8266_NODEMCU_ESP12E
Timezone_Generic v1.9.1
DS323x_Generic v1.2.2
Connecting to HueNet1
...................
You're connected to the network, IP = 192.168.2.94
Packet received
Seconds since Jan 1 1900 = 3854581698
Unix time = 1645592898
The UTC time is 5:08:18
============================
05:08:18 Wed 23 Feb 2022 UTC
00:08:18 Wed 23 Feb 2022 EST
System Time UTC: Wed Feb 23 05:08:18 2022

============================
05:08:27 Wed 23 Feb 2022 UTC
00:08:27 Wed 23 Feb 2022 EST
System Time UTC: Wed Feb 23 05:08:28 2022

============================
05:08:37 Wed 23 Feb 2022 UTC
00:08:37 Wed 23 Feb 2022 EST
System Time UTC: Wed Feb 23 05:08:38 2022

============================
05:08:47 Wed 23 Feb 2022 UTC
00:08:47 Wed 23 Feb 2022 EST
System Time UTC: Wed Feb 23 05:08:48 2022

============================
05:08:57 Wed 23 Feb 2022 UTC
00:08:57 Wed 23 Feb 2022 EST
System Time UTC: Wed Feb 23 05:08:58 2022
```

Cheers,

**Comment by rnsi** [comment]
That's perfect!

Thank you very much for your quick response and solution. It is very much appreciated.

**Comment by khoih-prog** [comment]
Hi @rnsi 

The new [**DS323x_Generic releases v1.2.3**](https://github.com/khoih-prog/DS323x_Generic/releases/tag/v1.2.3) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/DS323x_Generic#contributions-and-thanks)

Best Regards,

---

### Releases v1.2.3

1. Optimize code by using passing by `reference` instead of by `value`
1. Add `ESP_Complex` examples to update system time from RTC time. Check [**setTime() does not set system time** #1](https://github.com/khoih-prog/DS323x_Generic/issues/1)
2. Update `Packages' Patches`
