### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by rnsi** [khoih-prog/DS323x_Generic#2]
The DS332331 has a Digital Temp Sensor Output which is used for time keeping, but can also be read at registers 11h and 12h. Would you have any interest adding this function?

**Comment by khoih-prog** [comment]
Already in the library as

```
float temperature()
```

at

https://github.com/khoih-prog/DS323x_Generic/blob/349f18f19630fed579e159f9d65f06e45a97ba1e/src/DS323x_Generic.h#L698-L707

Thanks anyway,

Regards,
